### ISSUE TITLE
Cannot be used with React 16

### ISSUE THREAD

**Issue by danott** [souporserious/react-midnight#18]
This project cannot be used with React 16+. Console warnings informed me that we need to replace `React.PropTypes` with standalone `PropTypes` package.

**Comment by souporserious** [comment]
Fixed [here](https://github.com/souporserious/react-midnight/pull/19) and published under `0.7.2` 🎉

**Comment by danott** [comment]
🎉 Thanks ma'dude!

**Comment by souporserious** [comment]
Thank @glosie ❤️
